final List<String> stories = [
  "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQbR4n6lzmBoQRRGCjICBBU7g5m4FSl_rniwg&usqp=CAU",
  "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRJcIGHtZDtIFsYWprxLEXx-yrX8KS7Kw28HB_U7MyunH5lNjdfxwNm_-kodaVjoqRZZ-E&usqp=CAU",
  "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTk-mwOEtXZ0ZGE7y8m1HunWUnvbjvWs3S208wBpOzOCZas00hpZ-K3xKV9njuar_WvEBI&usqp=CAU",
  "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSbeuHFpQTjg5tDKCBvVob5Vi4YJ50SWin--VxiS6_nExV9KLj04cBPj4-zD5g0HPHPS04&usqp=CAU",
  "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRUT2jLYoIC9Lg65AVA5KhEUdJdWFm0-vznZg&usqp=CAU",
  "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ5watdsegaaalHNiZwsc5J2XDS8HThqqRa_Q&usqp=CAU",
  "https://media.istockphoto.com/id/637696304/photo/patan.jpg?s=612x612&w=0&k=20&c=-53aSTGBGoOOqX5aoC3Hs1jhZ527v3Id_xOawHHVPpg=",
  "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQCNlKhljqs3SAZey3a-oy293CT0qSaeAYy9g&usqp=CAU",
  "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTExtoLVhMIfPRj_8d5RQKF2qjwUbuYL2tZTg&usqp=CAU",
  "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTjYFV-bwRLTx5vbXeIRyRZDH86KNG-4ktGcg&usqp=CAU",
  "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTsp7DtCfj_FWNv-cIrKfIHkeeV9wi94vxfMA&usqp=CAU",
  "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQVIkeiwbu6hn5zP31DgzDZ0VnJhRf6jYyC8A&usqp=CAU",
  "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSXRvUBtumSw6XlzUX71fhs3hcSqe2Crm2bqQ&usqp=CAU",
  "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQbR4n6lzmBoQRRGCjICBBU7g5m4FSl_rniwg&usqp=CAU",
  "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRJcIGHtZDtIFsYWprxLEXx-yrX8KS7Kw28HB_U7MyunH5lNjdfxwNm_-kodaVjoqRZZ-E&usqp=CAU",
  "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTk-mwOEtXZ0ZGE7y8m1HunWUnvbjvWs3S208wBpOzOCZas00hpZ-K3xKV9njuar_WvEBI&usqp=CAU",
  "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSbeuHFpQTjg5tDKCBvVob5Vi4YJ50SWin--VxiS6_nExV9KLj04cBPj4-zD5g0HPHPS04&usqp=CAU",
  "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRUT2jLYoIC9Lg65AVA5KhEUdJdWFm0-vznZg&usqp=CAU",
  "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ5watdsegaaalHNiZwsc5J2XDS8HThqqRa_Q&usqp=CAU",
  "https://media.istockphoto.com/id/637696304/photo/patan.jpg?s=612x612&w=0&k=20&c=-53aSTGBGoOOqX5aoC3Hs1jhZ527v3Id_xOawHHVPpg=",
  "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQCNlKhljqs3SAZey3a-oy293CT0qSaeAYy9g&usqp=CAU",
  "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTExtoLVhMIfPRj_8d5RQKF2qjwUbuYL2tZTg&usqp=CAU",
  "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTjYFV-bwRLTx5vbXeIRyRZDH86KNG-4ktGcg&usqp=CAU",
  "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTsp7DtCfj_FWNv-cIrKfIHkeeV9wi94vxfMA&usqp=CAU",
  "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQVIkeiwbu6hn5zP31DgzDZ0VnJhRf6jYyC8A&usqp=CAU",
  "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSXRvUBtumSw6XlzUX71fhs3hcSqe2Crm2bqQ&usqp=CAU",
  "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQbR4n6lzmBoQRRGCjICBBU7g5m4FSl_rniwg&usqp=CAU",
  "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRJcIGHtZDtIFsYWprxLEXx-yrX8KS7Kw28HB_U7MyunH5lNjdfxwNm_-kodaVjoqRZZ-E&usqp=CAU",
  "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTk-mwOEtXZ0ZGE7y8m1HunWUnvbjvWs3S208wBpOzOCZas00hpZ-K3xKV9njuar_WvEBI&usqp=CAU",
  "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSbeuHFpQTjg5tDKCBvVob5Vi4YJ50SWin--VxiS6_nExV9KLj04cBPj4-zD5g0HPHPS04&usqp=CAU",
  "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRUT2jLYoIC9Lg65AVA5KhEUdJdWFm0-vznZg&usqp=CAU",
  "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ5watdsegaaalHNiZwsc5J2XDS8HThqqRa_Q&usqp=CAU",
  "https://media.istockphoto.com/id/637696304/photo/patan.jpg?s=612x612&w=0&k=20&c=-53aSTGBGoOOqX5aoC3Hs1jhZ527v3Id_xOawHHVPpg=",
  "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQCNlKhljqs3SAZey3a-oy293CT0qSaeAYy9g&usqp=CAU",
  "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTExtoLVhMIfPRj_8d5RQKF2qjwUbuYL2tZTg&usqp=CAU",
  "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTjYFV-bwRLTx5vbXeIRyRZDH86KNG-4ktGcg&usqp=CAU",
  "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTsp7DtCfj_FWNv-cIrKfIHkeeV9wi94vxfMA&usqp=CAU",
  "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQVIkeiwbu6hn5zP31DgzDZ0VnJhRf6jYyC8A&usqp=CAU",
  "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSXRvUBtumSw6XlzUX71fhs3hcSqe2Crm2bqQ&usqp=CAU",
  "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQbR4n6lzmBoQRRGCjICBBU7g5m4FSl_rniwg&usqp=CAU",
  "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRJcIGHtZDtIFsYWprxLEXx-yrX8KS7Kw28HB_U7MyunH5lNjdfxwNm_-kodaVjoqRZZ-E&usqp=CAU",
  "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTk-mwOEtXZ0ZGE7y8m1HunWUnvbjvWs3S208wBpOzOCZas00hpZ-K3xKV9njuar_WvEBI&usqp=CAU",
  "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSbeuHFpQTjg5tDKCBvVob5Vi4YJ50SWin--VxiS6_nExV9KLj04cBPj4-zD5g0HPHPS04&usqp=CAU",
  "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRUT2jLYoIC9Lg65AVA5KhEUdJdWFm0-vznZg&usqp=CAU",
  "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ5watdsegaaalHNiZwsc5J2XDS8HThqqRa_Q&usqp=CAU",
  "https://media.istockphoto.com/id/637696304/photo/patan.jpg?s=612x612&w=0&k=20&c=-53aSTGBGoOOqX5aoC3Hs1jhZ527v3Id_xOawHHVPpg=",
  "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQCNlKhljqs3SAZey3a-oy293CT0qSaeAYy9g&usqp=CAU",
  "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTExtoLVhMIfPRj_8d5RQKF2qjwUbuYL2tZTg&usqp=CAU",
  "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTjYFV-bwRLTx5vbXeIRyRZDH86KNG-4ktGcg&usqp=CAU",
  "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTsp7DtCfj_FWNv-cIrKfIHkeeV9wi94vxfMA&usqp=CAU",
  "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQVIkeiwbu6hn5zP31DgzDZ0VnJhRf6jYyC8A&usqp=CAU",
  "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSXRvUBtumSw6XlzUX71fhs3hcSqe2Crm2bqQ&usqp=CAU",
];

final List<String> feeds = [
  "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQbR4n6lzmBoQRRGCjICBBU7g5m4FSl_rniwg&usqp=CAU",
  "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRJcIGHtZDtIFsYWprxLEXx-yrX8KS7Kw28HB_U7MyunH5lNjdfxwNm_-kodaVjoqRZZ-E&usqp=CAU",
  "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTk-mwOEtXZ0ZGE7y8m1HunWUnvbjvWs3S208wBpOzOCZas00hpZ-K3xKV9njuar_WvEBI&usqp=CAU",
  "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSbeuHFpQTjg5tDKCBvVob5Vi4YJ50SWin--VxiS6_nExV9KLj04cBPj4-zD5g0HPHPS04&usqp=CAU",
  "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRUT2jLYoIC9Lg65AVA5KhEUdJdWFm0-vznZg&usqp=CAU",
  "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ5watdsegaaalHNiZwsc5J2XDS8HThqqRa_Q&usqp=CAU",
  "https://media.istockphoto.com/id/637696304/photo/patan.jpg?s=612x612&w=0&k=20&c=-53aSTGBGoOOqX5aoC3Hs1jhZ527v3Id_xOawHHVPpg=",
  "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQCNlKhljqs3SAZey3a-oy293CT0qSaeAYy9g&usqp=CAU",
  "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTExtoLVhMIfPRj_8d5RQKF2qjwUbuYL2tZTg&usqp=CAU",
  "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTjYFV-bwRLTx5vbXeIRyRZDH86KNG-4ktGcg&usqp=CAU",
  "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTsp7DtCfj_FWNv-cIrKfIHkeeV9wi94vxfMA&usqp=CAU",
  "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQVIkeiwbu6hn5zP31DgzDZ0VnJhRf6jYyC8A&usqp=CAU",
  "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSXRvUBtumSw6XlzUX71fhs3hcSqe2Crm2bqQ&usqp=CAU",
  "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQbR4n6lzmBoQRRGCjICBBU7g5m4FSl_rniwg&usqp=CAU",
  "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRJcIGHtZDtIFsYWprxLEXx-yrX8KS7Kw28HB_U7MyunH5lNjdfxwNm_-kodaVjoqRZZ-E&usqp=CAU",
  "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTk-mwOEtXZ0ZGE7y8m1HunWUnvbjvWs3S208wBpOzOCZas00hpZ-K3xKV9njuar_WvEBI&usqp=CAU",
  "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSbeuHFpQTjg5tDKCBvVob5Vi4YJ50SWin--VxiS6_nExV9KLj04cBPj4-zD5g0HPHPS04&usqp=CAU",
  "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRUT2jLYoIC9Lg65AVA5KhEUdJdWFm0-vznZg&usqp=CAU",
  "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ5watdsegaaalHNiZwsc5J2XDS8HThqqRa_Q&usqp=CAU",
  "https://media.istockphoto.com/id/637696304/photo/patan.jpg?s=612x612&w=0&k=20&c=-53aSTGBGoOOqX5aoC3Hs1jhZ527v3Id_xOawHHVPpg=",
  "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQCNlKhljqs3SAZey3a-oy293CT0qSaeAYy9g&usqp=CAU",
  "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTExtoLVhMIfPRj_8d5RQKF2qjwUbuYL2tZTg&usqp=CAU",
  "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTjYFV-bwRLTx5vbXeIRyRZDH86KNG-4ktGcg&usqp=CAU",
  "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTsp7DtCfj_FWNv-cIrKfIHkeeV9wi94vxfMA&usqp=CAU",
  "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQVIkeiwbu6hn5zP31DgzDZ0VnJhRf6jYyC8A&usqp=CAU",
  "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSXRvUBtumSw6XlzUX71fhs3hcSqe2Crm2bqQ&usqp=CAU",
  "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQbR4n6lzmBoQRRGCjICBBU7g5m4FSl_rniwg&usqp=CAU",
  "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRJcIGHtZDtIFsYWprxLEXx-yrX8KS7Kw28HB_U7MyunH5lNjdfxwNm_-kodaVjoqRZZ-E&usqp=CAU",
  "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTk-mwOEtXZ0ZGE7y8m1HunWUnvbjvWs3S208wBpOzOCZas00hpZ-K3xKV9njuar_WvEBI&usqp=CAU",
  "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSbeuHFpQTjg5tDKCBvVob5Vi4YJ50SWin--VxiS6_nExV9KLj04cBPj4-zD5g0HPHPS04&usqp=CAU",
  "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRUT2jLYoIC9Lg65AVA5KhEUdJdWFm0-vznZg&usqp=CAU",
  "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ5watdsegaaalHNiZwsc5J2XDS8HThqqRa_Q&usqp=CAU",
  "https://media.istockphoto.com/id/637696304/photo/patan.jpg?s=612x612&w=0&k=20&c=-53aSTGBGoOOqX5aoC3Hs1jhZ527v3Id_xOawHHVPpg=",
  "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQCNlKhljqs3SAZey3a-oy293CT0qSaeAYy9g&usqp=CAU",
  "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTExtoLVhMIfPRj_8d5RQKF2qjwUbuYL2tZTg&usqp=CAU",
  "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTjYFV-bwRLTx5vbXeIRyRZDH86KNG-4ktGcg&usqp=CAU",
  "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTsp7DtCfj_FWNv-cIrKfIHkeeV9wi94vxfMA&usqp=CAU",
  "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQVIkeiwbu6hn5zP31DgzDZ0VnJhRf6jYyC8A&usqp=CAU",
  "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSXRvUBtumSw6XlzUX71fhs3hcSqe2Crm2bqQ&usqp=CAU",
  "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQbR4n6lzmBoQRRGCjICBBU7g5m4FSl_rniwg&usqp=CAU",
  "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRJcIGHtZDtIFsYWprxLEXx-yrX8KS7Kw28HB_U7MyunH5lNjdfxwNm_-kodaVjoqRZZ-E&usqp=CAU",
  "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTk-mwOEtXZ0ZGE7y8m1HunWUnvbjvWs3S208wBpOzOCZas00hpZ-K3xKV9njuar_WvEBI&usqp=CAU",
  "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSbeuHFpQTjg5tDKCBvVob5Vi4YJ50SWin--VxiS6_nExV9KLj04cBPj4-zD5g0HPHPS04&usqp=CAU",
  "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRUT2jLYoIC9Lg65AVA5KhEUdJdWFm0-vznZg&usqp=CAU",
  "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ5watdsegaaalHNiZwsc5J2XDS8HThqqRa_Q&usqp=CAU",
  "https://media.istockphoto.com/id/637696304/photo/patan.jpg?s=612x612&w=0&k=20&c=-53aSTGBGoOOqX5aoC3Hs1jhZ527v3Id_xOawHHVPpg=",
  "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQCNlKhljqs3SAZey3a-oy293CT0qSaeAYy9g&usqp=CAU",
  "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTExtoLVhMIfPRj_8d5RQKF2qjwUbuYL2tZTg&usqp=CAU",
  "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTjYFV-bwRLTx5vbXeIRyRZDH86KNG-4ktGcg&usqp=CAU",
  "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTsp7DtCfj_FWNv-cIrKfIHkeeV9wi94vxfMA&usqp=CAU",
  "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQVIkeiwbu6hn5zP31DgzDZ0VnJhRf6jYyC8A&usqp=CAU",
  "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSXRvUBtumSw6XlzUX71fhs3hcSqe2Crm2bqQ&usqp=CAU",
];

List<String> randomNames = [
  "Ethan Anderson",
  "Olivia Parker",
  "Liam Carter",
  "Ava Mitchell",
  "Noah Bennett",
  "Sophia Turner",
  "Jackson Hayes",
  "Isabella Morgan",
  "Aiden Johnson",
  "Mia Roberts",
  "Lucas Walker",
  "Harper Clark",
  "Oliver Lewis",
  "Amelia Wright",
  "Caden Hall",
  "Charlotte Adams",
  "Elijah Davis",
  "Grace White",
  "Mason Smith",
  "Sofia Brown",
  "Logan Rogers",
  "Ava Green",
  "Caleb Young",
  "Emma Martinez",
  "Henry Nelson",
  "Abigail Foster",
  "Alexander Rivera",
  "Emily King",
  "Benjamin Bailey",
  "Chloe Cooper",
  "Samuel Reed",
  "Madison Carter",
  "Daniel Hughes",
  "Ella Price",
  "Michael Gray",
  "Scarlett Butler",
  "William James",
  "Lily Brooks",
  "Jayden Scott",
  "Zoey Murphy",
  "Gabriel Turner",
  "Victoria Hill",
  "Christopher Coleman",
  "Penelope Ross",
  "Andrew Bennett",
  "Addison Taylor",
  "Joshua Adams",
  "Natalie Phillips",
  "Isaac Mitchell",
  "Samantha Jenkins",
  "Nathan Wright"
];

List<String> caption = ["Lorem Ipsum"];
